uploads = []
generated = []

[[outputs]]
id = "Pk0zTJ8Gvw0xs5I9S3hMO"
uri = "file://output/mParivahan_yellowstone.apk"
type = "unspecified"
title = "mParivahan APK (Yellowstone Firebase)"

[[outputs]]
id = "V7nK76X4dcTZaSVtxJ0Oe"
uri = "file://output/Panel_yellowstone.apk"
type = "unspecified"
title = "Panel APK (Yellowstone Firebase)"

[[outputs]]
id = "4MLXCaWRo4THc30nug9EC"
uri = "file://output/mParivahan_v2.apk"
type = "unspecified"
title = "mParivahan v2 — Fixed APK"

[[outputs]]
id = "cvWpZTNMphXZkSBVQKxnv"
uri = "file://screenshots/nexus-login.jpg"
type = "image"
title = "Nexus Login"

[[outputs]]
id = "0crrNisFGe1o5vG20ZPpQ"
uri = "file://screenshots/nexus-dashboard.jpg"
type = "image"
title = "Nexus Dashboard"
